name: Rust build checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@v1.2
    - name: Conan version
      run: echo "${{ steps.conan.outputs.version }}"
    - name: Conan profile init
      run: conan profile detect
    - name: Run tests
      run: cargo test --verbose -- --test-threads=1
    - name: Test build the example crates
      run: |
        cargo build -p example-build-script -vv
        cargo build -p example-build-script -vv --release
    - name: Test run the build script example
      run: cargo run -p example-build-script
  fmt:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run cargo fmt
      run: cargo fmt -- --check
  clippy:
    name: Clippy lints
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run cargo clippy
      run: cargo clippy --tests -- --deny warnings
